export const colors = {
  background: "#f8f4ec",
  surface: "#fffdf8",
  surfaceMuted: "#f0eadf",
  border: "#ded4c6",
  text: "#2f241d",
  textMuted: "#6d5d51",
  accent: "#bb6c3f",
  accentSoft: "#f6e1d4",
  success: "#3f7d4d",
  danger: "#b5483f",
  white: "#ffffff",
  heatmapDone: "#3f7d4d",
  heatmapSkipped: "#e6d3a8",
  heatmapMissed: "#f0eadf",
  heatmapTodayOutline: "#ded4c6",
};
